name: ✨ Feature Request
description: Suggest a new feature or enhancement for Evolution Manager
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Please fill out the form below with as much detail as possible.

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting your feature request
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested before
          required: true
        - label: I have read the [documentation](https://doc.evolution-api.com)
          required: true
        - label: This feature request is related to Evolution Manager (not Evolution API)
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe the problem you're trying to solve
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered
      placeholder: I have also considered...

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which category does this feature belong to?
      options:
        - UI/UX Improvement
        - New Integration
        - Performance Enhancement
        - Security Enhancement
        - Developer Experience
        - Accessibility
        - Internationalization
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my workflow
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case and how this feature would help
      placeholder: In my workflow, I need to...
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Screenshots
      description: If applicable, add mockups, wireframes, or screenshots to help explain your feature
      placeholder: Drag and drop images here or paste image URLs

  - type: textarea
    id: technical-details
    attributes:
      label: Technical Details
      description: If you have technical knowledge, please provide any relevant technical details or implementation suggestions
      placeholder: This could be implemented by...

  - type: checkboxes
    id: impact
    attributes:
      label: Impact Assessment
      description: Please check all that apply
      options:
        - label: This feature would benefit many users
        - label: This feature is backward compatible
        - label: This feature requires breaking changes
        - label: This feature affects security
        - label: This feature affects performance

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, links, or references about the feature request here
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to contribute to implementing this feature?
      options:
        - label: I would like to work on implementing this feature
          required: false
        - label: I can provide design mockups
          required: false
        - label: I can help with testing
          required: false
